# Generated by Django 3.2 on 2021-04-19 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='programmed_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 9, 4, 2, 858706)),
        ),
    ]
